In [47]:
!pip install pandas

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in C:\Users\ANKIT TRIPATHI\AppData\Roaming\Python\Python313\site-packages (2.3.2)
Requirement already satisfied: numpy>=1.26.0 in C:\Users\ANKIT TRIPATHI\AppData\Roaming\Python\Python313\site-packages (from pandas) (2.2.6)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\ANKIT TRIPATHI\AppData\Roaming\Python\Python313\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in C:\Users\ANKIT TRIPATHI\AppData\Roaming\Python\Python313\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in C:\Users\ANKIT TRIPATHI\AppData\Roaming\Python\Python313\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in C:\Users\ANKIT TRIPATHI\AppData\Roaming\Python\Python313\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [48]:
import pandas as pd

In [49]:
pd.__version__

'2.3.2'

In [50]:
# Creating dataframe
df = pd.DataFrame([10,20,30], columns = ['Col_Name'])
print(df)

   Col_Name
0        10
1        20
2        30

In [51]:
print(type(df))

<class 'pandas.core.frame.DataFrame'>

In [52]:
data = {
    "Name" : ["Ankit","Devendra","Ramprit","Prabhanshu"],
    "Age" : [21,22,22,20],
    "Salary" : [500000,450000,300000,250000]
}

In [53]:
df = pd.DataFrame(data)
print(df)

         Name  Age  Salary
0       Ankit   21  500000
1    Devendra   22  450000
2     Ramprit   22  300000
3  Prabhanshu   20  250000

In [54]:
df.head() # Top rows
df.head(2)

       Name  Age  Salary
0     Ankit   21  500000
1  Devendra   22  450000

In [55]:
df.tail(2)

         Name  Age  Salary
2     Ramprit   22  300000
3  Prabhanshu   20  250000

In [56]:
df.shape

(4, 3)

In [57]:
df.columns

Index(['Name', 'Age', 'Salary'], dtype='object')

In [58]:
df.rename(columns = {"Name" : "First_Name"},inplace = True)

In [59]:
df

   First_Name  Age  Salary
0       Ankit   21  500000
1    Devendra   22  450000
2     Ramprit   22  300000
3  Prabhanshu   20  250000

In [60]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   First_Name  4 non-null      object
 1   Age         4 non-null      int64
 2   Salary      4 non-null      int64
dtypes: int64(2), object(1)
memory usage: 228.0+ bytes

In [61]:
df.describe()  # Statistical summary

             Age         Salary
count   4.000000       4.000000
mean   21.250000  375000.000000
std     0.957427  119023.807142
min    20.000000  250000.000000
25%    20.750000  287500.000000
50%    21.500000  375000.000000
75%    22.000000  462500.000000
max    22.000000  500000.000000

In [62]:
# To save and load the data
df.to_csv('Test_data.csv',index = False)

In [63]:
load_data = pd.read_csv('Test_data.csv')
print(load_data)

   First_Name  Age  Salary
0       Ankit   21  500000
1    Devendra   22  450000
2     Ramprit   22  300000
3  Prabhanshu   20  250000

In [64]:
# Rows and Columns -Selection
df[['First_Name']]

   First_Name
0       Ankit
1    Devendra
2     Ramprit
3  Prabhanshu

In [65]:
df[['First_Name','Salary']]

   First_Name  Salary
0       Ankit  500000
1    Devendra  450000
2     Ramprit  300000
3  Prabhanshu  250000

In [66]:
# Select Rows
# loc -- > filters data on the basis of label
# df.loc[df.Age == 22]
df.loc[0:2]

  First_Name  Age  Salary
0      Ankit   21  500000
1   Devendra   22  450000
2    Ramprit   22  300000

In [67]:
# iloc --> index-value based
df.iloc[0:2]

  First_Name  Age  Salary
0      Ankit   21  500000
1   Devendra   22  450000

In [68]:
# filter data 
# df['Age'] > 18
df_age_filter = df[df['Age'] >=22]
print(df_age_filter)

  First_Name  Age  Salary
1   Devendra   22  450000
2    Ramprit   22  300000

In [69]:
df.where(df['Age'] >= 22)

  First_Name   Age    Salary
0        NaN   NaN       NaN
1   Devendra  22.0  450000.0
2    Ramprit  22.0  300000.0
3        NaN   NaN       NaN

In [70]:
# Rows and Columns --. Operations(Add,Update, Delete)
df['Post'] = ['CEO','HR','CTO','DA']

In [71]:
df

   First_Name  Age  Salary Post
0       Ankit   21  500000  CEO
1    Devendra   22  450000   HR
2     Ramprit   22  300000  CTO
3  Prabhanshu   20  250000   DA

In [72]:
df['Bonus'] = df['Salary'] * 0.2
df

   First_Name  Age  Salary Post     Bonus
0       Ankit   21  500000  CEO  100000.0
1    Devendra   22  450000   HR   90000.0
2     Ramprit   22  300000  CTO   60000.0
3  Prabhanshu   20  250000   DA   50000.0

In [73]:
# Add new cell
df.loc[len(df)] = ['Himanshu',21,400000,'IT',5000]
df

   First_Name  Age  Salary Post     Bonus
0       Ankit   21  500000  CEO  100000.0
1    Devendra   22  450000   HR   90000.0
2     Ramprit   22  300000  CTO   60000.0
3  Prabhanshu   20  250000   DA   50000.0
4    Himanshu   21  400000   IT    5000.0

In [74]:
# Update Value using index 
df.loc[0, 'Salary'] = 4500000
df

   First_Name  Age   Salary Post     Bonus
0       Ankit   21  4500000  CEO  100000.0
1    Devendra   22   450000   HR   90000.0
2     Ramprit   22   300000  CTO   60000.0
3  Prabhanshu   20   250000   DA   50000.0
4    Himanshu   21   400000   IT    5000.0

In [75]:
# update value --> using the column value
df.loc[df.Age == 22 , 'Salary'] = 152555
df

   First_Name  Age   Salary Post     Bonus
0       Ankit   21  4500000  CEO  100000.0
1    Devendra   22   152555   HR   90000.0
2     Ramprit   22   152555  CTO   60000.0
3  Prabhanshu   20   250000   DA   50000.0
4    Himanshu   21   400000   IT    5000.0

In [76]:
# Delete value 
df_drop = df.drop(df[df.First_Name == 'Ankit'].index)
df_drop

   First_Name  Age  Salary Post    Bonus
1    Devendra   22  152555   HR  90000.0
2     Ramprit   22  152555  CTO  60000.0
3  Prabhanshu   20  250000   DA  50000.0
4    Himanshu   21  400000   IT   5000.0

In [77]:
df.drop('Bonus' , axis = 1,inplace = True)

In [78]:
df

   First_Name  Age   Salary Post
0       Ankit   21  4500000  CEO
1    Devendra   22   152555   HR
2     Ramprit   22   152555  CTO
3  Prabhanshu   20   250000   DA
4    Himanshu   21   400000   IT

In [79]:
# Sort values
df.sort_values('Salary',ascending=False)

   First_Name  Age   Salary Post
0       Ankit   21  4500000  CEO
4    Himanshu   21   400000   IT
3  Prabhanshu   20   250000   DA
2     Ramprit   22   152555  CTO
1    Devendra   22   152555   HR

In [80]:
# Working with date 
df['DOJ'] = ['2024-02-01' ,'2024-01-02' ,'2024-03-01' ,'2024-04-01' , '2024-02-12' ]
df

   First_Name  Age   Salary Post         DOJ
0       Ankit   21  4500000  CEO  2024-02-01
1    Devendra   22   152555   HR  2024-01-02
2     Ramprit   22   152555  CTO  2024-03-01
3  Prabhanshu   20   250000   DA  2024-04-01
4    Himanshu   21   400000   IT  2024-02-12

In [81]:
df['DOJ'].dtype

dtype('O')

In [82]:
df['DOJ'] = pd.to_datetime(df['DOJ'])
df['DOJ'].dtype

dtype('<M8[ns]')

In [84]:
# Extract year, month, week, day

df['DOJ'].dt.year
df['DOJ'].dt.month
df['DOJ'].dt.day
df['DOJ'].dt.day_name()

0    Thursday
1     Tuesday
2      Friday
3      Monday
4      Monday
Name: DOJ, dtype: object

In [85]:
df['DOJ'] + pd.Timedelta(days=90)

0   2024-05-01
1   2024-04-01
2   2024-05-30
3   2024-06-30
4   2024-05-12
Name: DOJ, dtype: datetime64[ns]

In [86]:
df

   First_Name  Age   Salary Post        DOJ
0       Ankit   21  4500000  CEO 2024-02-01
1    Devendra   22   152555   HR 2024-01-02
2     Ramprit   22   152555  CTO 2024-03-01
3  Prabhanshu   20   250000   DA 2024-04-01
4    Himanshu   21   400000   IT 2024-02-12

In [87]:
# Aggregation and group by
df['Post'].value_counts()

Post
CEO    1
HR     1
CTO    1
DA     1
IT     1
Name: count, dtype: int64

In [89]:
df.groupby('Age')['Salary'].mean()

Age
20     250000.0
21    2450000.0
22     152555.0
Name: Salary, dtype: float64

In [90]:
df.groupby('First_Name').agg({'Salary' : 'mean', 'Age' : 'count'})

               Salary  Age
First_Name
Ankit       4500000.0    1
Devendra     152555.0    1
Himanshu     400000.0    1
Prabhanshu   250000.0    1
Ramprit      152555.0    1